# Generated by Django 3.0.3 on 2020-05-20 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20200520_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='topic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='first_app.Topic'),
        ),
    ]
